### PR TITLE
chore: add chart missing files

### PR DESCRIPTION
**Pull request by tomaszbarwicki**
PR to add missing helm chart LICENSE & README.md files.

Updates https://github.com/eclipse-tractusx/sig-infra/issues/287

### CODE REVIEW

**Review by almadigabor — APPROVED** [review]
There are some failed checks on the bottom.

**Comment by tomaszbarwicki** [comment]
> There are some failed checks on the bottom.
> 
> * You need to bump the chart version in the Chart.yaml because you added files to it and helm-chart-releaser can't release with an already existing chart version.
> * The quality checks are failed for 2 reasons: base image is not supported and resource limits are not set for pod

Issues addressed, except base image which is not on approved images list. Perhaps we can fix that later on.

**Comment by almadigabor** [comment]
Also updated the DEPENDENCIES file, opened IP issues and the following output was generated:

`[main] INFO A review is required for go/golang/golang.org%2Fx/tools/v0.8.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11052 .
[main] INFO A review is required for go/golang/github.com%2Fgoogle/gnostic-models/v0.6.9-0.20230804172637-c7be7c783f49.
[main] INFO A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10742 .
[main] INFO A review is required for go/golang/golang.org%2Fx/text/v0.13.0.
[main] INFO A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10752 .
[main] INFO A review is required for go/golang/golang.org%2Fx/sys/v0.13.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11053 .
[main] INFO A review is required for go/golang/github.com%2Fgo-task/slim-sprig/v0.0.0-20230315185526-52ccab3ef572.
[main] INFO A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10759 .
[main] INFO A review is required for go/golang/golang.org%2Fx/net/v0.17.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11054 .
[main] INFO A review is required for go/golang/golang.org%2Fx/oauth2/v0.13.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11055 .
[main] INFO A review is required for go/golang/golang.org%2Fx/term/v0.13.0.
[main] INFO A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11056 .`

**Review by FaGru3n — APPROVED** [review]
LGTM

**Pull request merged**
